### ISSUE TITLE
Canvas not loading after QR Scan

### ISSUE THREAD

**Issue by aarkay06** [ameybhavsar24/ww-wra#1]
I am getting the following error after scanning QR code in terminal....I first ran npm install then npm start and it seems that QR is successfully scanned but canvas is not loading.
![image](https://user-images.githubusercontent.com/88158135/128904621-f5d8a956-2cf3-4b9d-a680-c422d34b38f7.png)
And i have literally no experience in JS so i am not able to understand even a single line😢 Sorry For that

**Comment by aarkay06** [comment]
I got that,  I guess....I had joined multi device beta testing of WA...that's why it was not working....and when I left beta and tested again....The error didn't come but only Client is ready came written😅 and nothing is happening
![image](https://user-images.githubusercontent.com/88158135/128906047-531acd43-fb58-4c6b-8fec-7c3d804a941e.png)

**Comment by aarkay06** [comment]
Do I have to edit those lines that U have commented?

**Comment by ameybh** [comment]
Hello @KrishnaBros2,
The bot is up and running once you get "Client is ready!" message. Did you try sending a bot command on WhatsApp?
Try `!b hello` and you should get a response in WhatsApp.
Let me know otherwise alongwith any errors that are shown in the console.

I have updated `whatsapp-web.js` to `1.14.0` right now. Pull the new changes and install the updated packages.

**Comment by aarkay06** [comment]
Wow...Thanks for respoding and now it works....Thank You for making it🤩...By the way what are the commands that it responds to?

**Comment by ameybh** [comment]
You're welcome. You can try out any of the examples from https://www.wolframalpha.com/examples/. 😄

**Comment by aarkay06** [comment]
No not like that....one of my friend also used this and he used commands like !device (which tells the device of a person who meesaged ) , !joke and !insult...But when I am using these, there's no response

**Comment by aarkay06** [comment]
Ohh its like u made another package for that...ww-wra-goog this one....But I wanted to ask why different ones😅

**Comment by ameybh** [comment]
Oh, about that, I wrote a [article](https://dev.to/ameybhavsar/i-made-a-whatsapp-bot-to-solve-math-problems-6ab) describing basic use of a WhatsApp bot with Wolfram alpha API. This repository is simply the minimal code for that functionality. 
Otherwise, you can use ww-wra-goog if you'd like to try more features.
